### ISSUE TITLE
no unicode

### ISSUE THREAD

**Issue by 532910** [jes/eldood#1]
https://eldood.uk/010b75c2d3

![image](https://user-images.githubusercontent.com/14617699/176799954-dac7091c-8962-4eb6-becf-f0fa03348840.png)

**Comment by jes** [comment]
Fixed in https://github.com/jes/eldood/commit/dfdba63ff3c5b52b21b0e1c03430f1b72784b25f

Thank you!

**Comment by 532910** [comment]
Can confirm it works, thank you!
